matrix:
  include:
  - os: linux
    dist: xenial
    language: python
    python: "3.6"
  - os: linux
    dist: xenial
    language: python
    python: "3.7"
  - os: linux
    dist: bionic
    language: python
    python: "3.6"
  - os: linux
    dist: bionic
    language: python
    python: "3.7"

before_install:
  - sudo apt-get install liblapack-dev
  - sudo apt-get install ffmpeg

install:
  - pip install --upgrade pip
  - pip install jax==0.2.12 jaxlib==0.1.64
  - pip install tensorflow pytest flake8 jupyter matplotlib sklearn tqdm
  - pip install torch==1.3.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
  - pip install .

script:
  - pytest
  - flake8 cvxpylayers
  - jupyter nbconvert --ExecutePreprocessor.timeout=None --to notebook --execute examples/torch/data_poisoning_attack.ipynb examples/torch/convex_approximate_dynamic_programming.ipynb
  - jupyter nbconvert --ExecutePreprocessor.timeout=None --to notebook --execute examples/tf/data_poisoning_attack.ipynb examples/tf/convex_approximate_dynamic_programming.ipynb

notifications:
  email:
    # generated using travis encrypt, to prevent spam from forks
    - secure: "x7vPeYt/KnwiBHd8SykS8orTMyzQYJOBdZTi/AHQQDueCC+Fu9Z+PH+49t7OtoPYbWXNk74p1GhafyJgQUx4byUunM8+ULHYJ9zx+yZTvNUBD0h+iroZTaPSoz/bocPy5gjB7N7YYRWKsXDq/xnhPhiK3s6ANg2ljsiwA1t90zHC0Z1W4+jNWtAYOthELiWuoMVDnRyZ0zU8IRL/NpHXf+ApalVsm3CgJltLtT+EM1+SjVyorBLCkTGo5vFgweHpyi9VZBzonQQ0djvLgQCgMlczsNmqACliYq6YbFWMUvovuCyozomnElHgxgj4UI3slH4aeX5avnhosRbCAY5q3ldmXeLYjf79SdMKGktmq7RQvw1nXGsfg8xPMMQSyfiNgzPpq/bT/NTzyYn8NmB7DGSTP9bnxGFy5YKetmAl07mC2B15UqTgvKR4p3JBe6wumjUQyva89XrJSFqD0QJTBK3uIEkFTKsD2X40iO73lJt9mOfB1hrOmjl7i22P8+B0pBQFp6JPZ+fURrBYJ2pMRohVVe7rDPy2cghVrXzvElkaKabmtcEoWHzJSPLN2nJG3e6w3eK2LAu8HXgwgDpqhQwl/DEpL0HI8otCv8nqkj57C/w1HLpOOKGSHcdTVz37milT1gcT5H8ikSubrAu4XH6eITOGLbXIKtG3uyfxy1Y="
    - secure: "3rKTo2VkHKNWOeJ0zuFeWEytamnSspNKya1KHD5Bn4KVS7v2063RuUMJqpfrhHerecHBEWT6KC9XiibSBssY8FJJpDdNgd95rm+gjIUTVA2t4Pf9Nx1H9sA6X/BbQHmI9OvY8uDJYvP28Ve3q3BCM6+OvLKVjd/a/MVsxjLsQFSI/42LafK0kL5knlpva5+lHlLXUnrvSXc3TrLOCh/4BBTSXbpFXQjAhjuXYKxWjDo/Ut7jWcaNJWHAO/HmkG8Nz6DNEv2ehA30qjWUsR6po7Rq8yXaH6/dWCQLkvI9Th6h8VQfUjC16RdOeXHPzoCVhxfEOlqrqZkQcMl1BjO4JkaDQJg0wxoDAjcXEJTxarRD6rn6fHQGCnifsGCUuXLBlIHcTdEi20AxUG2WYqcSb5y8tbKt4oBdyEvxG8FBaA5gjSpOB6dx2f/+6dNyywhsiG90qthUEmb3SVBtgb/mfzVI0THa3oMIoiZdgHyYvPK0MFIAIqmd90r0Pxywan43g9QEbTojYP65HWxlxn88Eora3myEIaoRS99oMS8RXUZCzqMaUVdAaETLFg5+7DGLtcAW9bFQMSTURYolq5W3j/guZRh0OY+o9AHZNrl7h2yZ+Tzne089cdGa6r8CfohA5utH4Eu1KGo32Mj0xoG5Y/4ZWsJASfaOUb2XppWNbYA="

