name: build

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: |
            3.12
            3.11
            3.10
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: pip install cvxpy diffcp pytest torch[cpu] jax tensorflow-cpu
      - name: Run tests
        run: pytest

      - name: build
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        run: |
          pip install --upgrade build
          python -m build

      - name: publish
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
    permissions:
      id-token: write
